[package]
name = "ninelives-kafka"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Optional Kafka telemetry sink for ninelives"
license.workspace = true
publish = true
repository.workspace = true
readme = "README.md"

[dependencies]
ninelives = { workspace = true }
tracing = "0.1"

# Heavy deps are optional
rdkafka = { version = "0.36", features = ["tokio"], optional = true }

[features]
client = ["rdkafka"]
