version: '3.8'
services:
  redpanda:
    image: docker.redpanda.com/redpanda/redpanda:v25.3.1
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 256M
      - --node-id
      - "0"
      - --check=true
    ports:
      - "9092:9092"
