[package]
name = "ninelives-otlp"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "OTLP telemetry sink for ninelives"
license.workspace = true
publish = true
repository.workspace = true
readme = "README.md"

[dependencies]
ninelives = { workspace = true }
tracing = "0.1"
tower-service = { workspace = true }

opentelemetry = { version = "0.21", optional = true }
opentelemetry-otlp = { version = "0.14", optional = true, default-features = true, features = ["grpc-tonic"] }
tokio = { version = "1", features = ["rt", "macros"], optional = true }

[features]
client = ["opentelemetry", "opentelemetry-otlp", "tokio"]
